export type wishlistDataType = {
  id: number;
  title: string;
  price: number;
  stock: boolean;
  imgUrl: string;
}[];
export const wishlistData = [
  {
    id: 1,
    title: "Green Capsicum",
    price: 10,
    stock: true,
    imgUrl: "/img/pages/wishlist/Green Capsicum.jpg",
  },
  {
    id: 2,
    title: "Chinese Cabbage",
    price: 20,
    stock: false,
    imgUrl: "/img/pages/wishlist/Chinese Cabbage.jpg",
  },
  {
    id: 3,
    title: "Fresh Sujapuri Mango",
    price: 33.99,
    stock: false,
    imgUrl: "/img/pages/wishlist/Fresh Sujapuri Mango.jpg",
  },
  {
    id: 4,
    title: "Green Capsicum",
    price: 10,
    stock: true,
    imgUrl: "/img/pages/wishlist/Green Capsicum.jpg",
  },
  {
    id: 5,
    title: "Chinese Cabbage",
    price: 20,
    stock: false,
    imgUrl: "/img/pages/wishlist/Chinese Cabbage.jpg",
  },
  {
    id: 6,
    title: "Fresh Sujapuri Mango",
    price: 33.99,
    stock: false,
    imgUrl: "/img/pages/wishlist/Fresh Sujapuri Mango.jpg",
  },
  {
    id: 7,
    title: "Green Capsicum",
    price: 10,
    stock: true,
    imgUrl: "/img/pages/wishlist/Green Capsicum.jpg",
  },
  {
    id: 8,
    title: "Chinese Cabbage",
    price: 20,
    stock: false,
    imgUrl: "/img/pages/wishlist/Chinese Cabbage.jpg",
  },
  {
    id: 9,
    title: "Fresh Sujapuri Mango",
    price: 33.99,
    stock: false,
    imgUrl: "/img/pages/wishlist/Fresh Sujapuri Mango.jpg",
  },
  {
    id: 10,
    title: "Green Capsicum",
    price: 10,
    stock: true,
    imgUrl: "/img/pages/wishlist/Green Capsicum.jpg",
  },
  {
    id: 11,
    title: "Chinese Cabbage",
    price: 20,
    stock: false,
    imgUrl: "/img/pages/wishlist/Chinese Cabbage.jpg",
  },
  {
    id: 12,
    title: "Fresh Sujapuri Mango",
    price: 33.99,
    stock: false,
    imgUrl: "/img/pages/wishlist/Fresh Sujapuri Mango.jpg",
  },
  {
    id: 13,
    title: "Green Capsicum",
    price: 10,
    stock: true,
    imgUrl: "/img/pages/wishlist/Green Capsicum.jpg",
  },
  {
    id: 14,
    title: "Chinese Cabbage",
    price: 20,
    stock: false,
    imgUrl: "/img/pages/wishlist/Chinese Cabbage.jpg",
  },
  {
    id: 15,
    title: "Fresh Sujapuri Mango",
    price: 33.99,
    stock: false,
    imgUrl: "/img/pages/wishlist/Fresh Sujapuri Mango.jpg",
  },
  {
    id: 16,
    title: "Green Capsicum",
    price: 10,
    stock: true,
    imgUrl: "/img/pages/wishlist/Green Capsicum.jpg",
  },
  {
    id: 17,
    title: "Chinese Cabbage",
    price: 20,
    stock: false,
    imgUrl: "/img/pages/wishlist/Chinese Cabbage.jpg",
  },
  {
    id: 18,
    title: "Fresh Sujapuri Mango",
    price: 33.99,
    stock: false,
    imgUrl: "/img/pages/wishlist/Fresh Sujapuri Mango.jpg",
  },
  {
    id: 19,
    title: "Green Capsicum",
    price: 10,
    stock: true,
    imgUrl: "/img/pages/wishlist/Green Capsicum.jpg",
  },
  {
    id: 20,
    title: "Chinese Cabbage",
    price: 20,
    stock: false,
    imgUrl: "/img/pages/wishlist/Chinese Cabbage.jpg",
  },
  {
    id: 21,
    title: "Fresh Sujapuri Mango",
    price: 33.99,
    stock: false,
    imgUrl: "/img/pages/wishlist/Fresh Sujapuri Mango.jpg",
  },
  {
    id: 22,
    title: "Green Capsicum",
    price: 10,
    stock: true,
    imgUrl: "/img/pages/wishlist/Green Capsicum.jpg",
  },
  {
    id: 23,
    title: "Chinese Cabbage",
    price: 20,
    stock: false,
    imgUrl: "/img/pages/wishlist/Chinese Cabbage.jpg",
  },
  {
    id: 24,
    title: "Fresh Sujapuri Mango",
    price: 33.99,
    stock: false,
    imgUrl: "/img/pages/wishlist/Fresh Sujapuri Mango.jpg",
  },
  {
    id: 25,
    title: "Green Capsicum",
    price: 10,
    stock: true,
    imgUrl: "/img/pages/wishlist/Green Capsicum.jpg",
  },
  {
    id: 26,
    title: "Chinese Cabbage",
    price: 20,
    stock: false,
    imgUrl: "/img/pages/wishlist/Chinese Cabbage.jpg",
  },
  {
    id: 27,
    title: "Fresh Sujapuri Mango",
    price: 33.99,
    stock: false,
    imgUrl: "/img/pages/wishlist/Fresh Sujapuri Mango.jpg",
  },

  {
    id: 28,
    title: "Green Capsicum",
    price: 10,
    stock: true,
    imgUrl: "/img/pages/wishlist/Green Capsicum.jpg",
  },
  {
    id: 29,
    title: "Chinese Cabbage",
    price: 20,
    stock: false,
    imgUrl: "/img/pages/wishlist/Chinese Cabbage.jpg",
  },
  {
    id: 30,
    title: "Fresh Sujapuri Mango",
    price: 33.99,
    stock: false,
    imgUrl: "/img/pages/wishlist/Fresh Sujapuri Mango.jpg",
  },

  {
    id: 31,
    title: "Green Capsicum",
    price: 10,
    stock: true,
    imgUrl: "/img/pages/wishlist/Green Capsicum.jpg",
  },
  {
    id: 32,
    title: "Chinese Cabbage",
    price: 20,
    stock: false,
    imgUrl: "/img/pages/wishlist/Chinese Cabbage.jpg",
  },
  {
    id: 33,
    title: "Fresh Sujapuri Mango",
    price: 33.99,
    stock: false,
    imgUrl: "/img/pages/wishlist/Fresh Sujapuri Mango.jpg",
  },

  {
    id: 34,
    title: "Green Capsicum",
    price: 10,
    stock: true,
    imgUrl: "/img/pages/wishlist/Green Capsicum.jpg",
  },
  {
    id: 35,
    title: "Chinese Cabbage",
    price: 20,
    stock: false,
    imgUrl: "/img/pages/wishlist/Chinese Cabbage.jpg",
  },
  {
    id: 36,
    title: "Fresh Sujapuri Mango",
    price: 33.99,
    stock: false,
    imgUrl: "/img/pages/wishlist/Fresh Sujapuri Mango.jpg",
  },

  {
    id: 37,
    title: "Green Capsicum",
    price: 10,
    stock: true,
    imgUrl: "/img/pages/wishlist/Green Capsicum.jpg",
  },
  {
    id: 38,
    title: "Chinese Cabbage",
    price: 20,
    stock: false,
    imgUrl: "/img/pages/wishlist/Chinese Cabbage.jpg",
  },
  {
    id: 39,
    title: "Fresh Sujapuri Mango",
    price: 33.99,
    stock: false,
    imgUrl: "/img/pages/wishlist/Fresh Sujapuri Mango.jpg",
  },

  {
    id: 40,
    title: "Green Capsicum",
    price: 10,
    stock: true,
    imgUrl: "/img/pages/wishlist/Green Capsicum.jpg",
  },
  {
    id: 41,
    title: "Chinese Cabbage",
    price: 20,
    stock: false,
    imgUrl: "/img/pages/wishlist/Chinese Cabbage.jpg",
  },
  {
    id: 42,
    title: "Fresh Sujapuri Mango",
    price: 33.99,
    stock: false,
    imgUrl: "/img/pages/wishlist/Fresh Sujapuri Mango.jpg",
  },
] as wishlistDataType;
